from enum import Enum


class ErrorCode(str, Enum):
    COUNTRIES_NOT_FOUND = "COUNTRIES_NOT_FOUND"
    COUNTRY_NOT_EXIST = "COUNTRY_NOT_EXIST"
    COUNTRY_BLOCK_NOT_EXIST = "COUNTRY_BLOCK_NOT_EXIST"
