version: "3.8"

services:
  db:
    image: postgres:15
    container_name: db_postgres
    command: -p 5432
    expose:
      - 5432
    env_file:
      - .env-prod
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - grigorishinbackend
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    expose:
      - 5050
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=saifulinvladislav@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=VLAD007vlad!
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
    volumes:
        - ./pgadmin-data:/var/lib/pgadmin
    networks:
      - grigorishinbackend
      - nginx
    restart: unless-stopped

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    env_file:
      - .env-prod
    command: ["/fastapi-app/docker/fastapi-app.sh"]
    expose:
      - 8000
    depends_on:
        - db
        - pgadmin
    networks:
      - grigorishinbackend
      - nginx

networks:
  grigorishinbackend:
    external: true
  nginx:
    external: true