"""Added schedule table

Revision ID: 5a52a1dcad09
Revises: 69a4cb5004e3
Create Date: 2023-08-02 16:14:32.296568

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5a52a1dcad09'
down_revision = '69a4cb5004e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
                    sa.Column('id', sa.Integer(), sa.Identity(always=True, increment=1), nullable=False),
                    sa.Column('start_time', sa.TIMESTAMP(), nullable=False),
                    sa.Column('end_time', sa.TIMESTAMP(), nullable=False),
                    sa.Column('course_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    # ### end Alembic commands ###
